snapshot: &snapshot
  working_directory: ~/repo
  steps:
    - checkout
    - run: 
        name: Install build dependencies
        command: |
          apt-get update -qq
          apt-get install -y bc qt5-default cmake dh-make git lsb-release
    - run:
        name: Create changelog
        command: |
          CODENAME=$(lsb_release --codename --short)
          RELEASE=$(lsb_release --release --short)
          ./changelog.sh startpage ${CODENAME} deb${RELEASE} > debian/changelog
      
    - run:
        name: Create source archive
        command: |
          export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          export GIT_COMMIT=${CIRCLE_SHA1:0:7}
          mkdir -p ~/repo/startpage_${GIT_TAG//v}+git-${GIT_COMMIT}
          tar -czf /tmp/startpage_${GIT_TAG//v}+git-${GIT_COMMIT}.orig.tar.gz .
          tar -xzf /tmp/startpage_${GIT_TAG//v}+git-${GIT_COMMIT}.orig.tar.gz -C ~/repo/startpage_${GIT_TAG//v}+git-${GIT_COMMIT}
          ls -l
    - run:
        name: Build package
        command: |
          export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          export GIT_COMMIT=${CIRCLE_SHA1:0:7}
          cd ~/repo/startpage_${GIT_TAG//v}+git-${GIT_COMMIT}
          dpkg-buildpackage -us -uc
    - run:
        name: Save build
        command: |
          export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          export GIT_COMMIT=${CIRCLE_SHA1:0:7}
          mkdir -p ~/build
          ls -l ~/repo
          mv ~/repo/*.deb ~/build/
    - store_artifacts:
        path: ~/build
    - persist_to_workspace:
        root: ~/
        paths:
          - build/*

version: 2
jobs:
  build-commit-debian-buster-amd64:
    docker:
      - image: debian:buster-slim
    <<: *snapshot
  build-commit-debian-stretch-amd64:
    docker:
      - image: debian:stretch-slim
    <<: *snapshot
  build-commit-debian-bullseye-amd64:
    docker:
      - image: debian:bullseye-slim
    <<: *snapshot
  build-commit-debian-buster-i386:
    docker:
      - image: i386/debian:buster-slim
    <<: *snapshot

workflows:
  version: 2
  snapshot:
    jobs:
      - build-commit-debian-buster-amd64
      - build-commit-debian-stretch-amd64
      - build-commit-debian-bullseye-amd64
      - build-commit-debian-buster-i386